In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn.neural_network import MLPClassifier, MLPRegressor

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
iris = pd.read_csv('http://bit.ly/Iris_flower_data')
iris

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
# Encode the categorical column
encode = LabelEncoder()


iris['Class'] = encode.fit_transform(iris[['Class']])

/Users/RyanMburu/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [7]:
iris

sepal-length  sepal-width  petal-length  petal-width  Class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

In [10]:
# Split into training and testing sets

X = iris.loc[:, 'sepal-length' : 'petal-width'].values
y = iris['Class'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [11]:
# Scale the values
scaler = StandardScaler()

#Fit the model
scaler.fit(X_train)

# Transform the values
X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)

In [16]:
# Fit the values on the NN model and perform predictions

NN = MLPClassifier(hidden_layer_sizes=(15, 15, 15), activation='relu', max_iter=500)

NN.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(15, 15, 15), max_iter=500)

In [20]:
# Predictions 

y_pred = NN.predict(X_test)

# Performance

print('Accuracy score : ', accuracy_score(y_test, y_pred))

print('-----------------------------------------------')

print (confusion_matrix(y_test,y_pred))

print('-----------------------------------------------')

print(classification_report(y_test,y_pred))

Accuracy score :  1.0
-----------------------------------------------
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
-----------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

